//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GRI_MCLEntities : DbContext
    {
        public GRI_MCLEntities()
            : base("name=GRI_MCLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_acct> tbl_acct { get; set; }
        public virtual DbSet<tbl_boxes> tbl_boxes { get; set; }
        public virtual DbSet<tbl_brand> tbl_brand { get; set; }
        public virtual DbSet<tbl_cat1> tbl_cat1 { get; set; }
        public virtual DbSet<tbl_cat2> tbl_cat2 { get; set; }
        public virtual DbSet<tbl_CEclass> tbl_CEclass { get; set; }
        public virtual DbSet<tbl_comp> tbl_comp { get; set; }
        public virtual DbSet<tbl_coo> tbl_coo { get; set; }
        public virtual DbSet<tbl_cst_type> tbl_cst_type { get; set; }
        public virtual DbSet<tbl_currncy> tbl_currncy { get; set; }
        public virtual DbSet<tbl_formulas> tbl_formulas { get; set; }
        public virtual DbSet<tbl_grpFAB> tbl_grpFAB { get; set; }
        public virtual DbSet<tbl_grpHdr> tbl_grpHdr { get; set; }
        public virtual DbSet<tbl_grpLbl> tbl_grpLbl { get; set; }
        public virtual DbSet<tbl_grppix> tbl_grppix { get; set; }
        public virtual DbSet<tbl_lang> tbl_lang { get; set; }
        public virtual DbSet<tbl_lbl> tbl_lbl { get; set; }
        public virtual DbSet<tbl_life_cycle> tbl_life_cycle { get; set; }
        public virtual DbSet<tbl_material> tbl_material { get; set; }
        public virtual DbSet<tbl_plant> tbl_plant { get; set; }
        public virtual DbSet<tbl_prodmgr> tbl_prodmgr { get; set; }
        public virtual DbSet<tbl_purch> tbl_purch { get; set; }
        public virtual DbSet<tbl_qtdtl> tbl_qtdtl { get; set; }
        public virtual DbSet<tbl_qtdtl_replicate> tbl_qtdtl_replicate { get; set; }
        public virtual DbSet<tbl_qthdr> tbl_qthdr { get; set; }
        public virtual DbSet<tbl_qtstatus> tbl_qtstatus { get; set; }
        public virtual DbSet<tbl_rep> tbl_rep { get; set; }
        public virtual DbSet<tbl_spclty> tbl_spclty { get; set; }
        public virtual DbSet<tbl_stat> tbl_stat { get; set; }
        public virtual DbSet<tbl_strlty> tbl_strlty { get; set; }
        public virtual DbSet<tbl_techhdng> tbl_techhdng { get; set; }
        public virtual DbSet<tbl_trait> tbl_trait { get; set; }
        public virtual DbSet<tbl_uom> tbl_uom { get; set; }
        public virtual DbSet<tbl_users> tbl_users { get; set; }
        public virtual DbSet<tbl_vend> tbl_vend { get; set; }
        public virtual DbSet<tbl_vendDtl> tbl_vendDtl { get; set; }
        public virtual DbSet<tbl_X_cat> tbl_X_cat { get; set; }
        public virtual DbSet<tbl_X_grpcomp> tbl_X_grpcomp { get; set; }
        public virtual DbSet<tbl_X_material> tbl_X_material { get; set; }
        public virtual DbSet<tbl_X_ref> tbl_X_ref { get; set; }
        public virtual DbSet<tbl_X_spclty> tbl_X_spclty { get; set; }
        public virtual DbSet<tbl_X_trait> tbl_X_trait { get; set; }
        public virtual DbSet<tbl_HScode> tbl_HScode { get; set; }
        public virtual DbSet<tbl_pix> tbl_pix { get; set; }
        public virtual DbSet<tbl_tech> tbl_tech { get; set; }
        public virtual DbSet<tbl_uom_old> tbl_uom_old { get; set; }
    }
}
