//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_X_ref
    {
        public int xref_comp_id { get; set; }
        public int xref_equiv_compid { get; set; }
        public Nullable<int> xref_FE_priority { get; set; }
        public Nullable<bool> xref_exact { get; set; }
        public Nullable<int> xref_life_cycle_id { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_comp tbl_comp { get; set; }
        public virtual tbl_comp tbl_comp1 { get; set; }
    }
}
