//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_currncy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_currncy()
        {
            this.tbl_purch = new HashSet<tbl_purch>();
        }
    
        public int id { get; set; }
        public string currncy_name { get; set; }
        public string currncy_code { get; set; }
        public string currncy_symb { get; set; }
        public Nullable<double> currncy_rate { get; set; }
        public Nullable<int> currncy_base { get; set; }
        public Nullable<System.DateTime> currncy_dateUpdt { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_purch> tbl_purch { get; set; }
    }
}
