//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_users
    {
        public int id { get; set; }
        public string user_fname { get; set; }
        public string user_lname { get; set; }
        public string user_username { get; set; }
        public string user_password { get; set; }
    }
}
