//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_qtstatus
    {
        public int id { get; set; }
        public Nullable<int> qtstatus_order { get; set; }
        public string qtstatus_desc { get; set; }
        public string qtstatus_defn { get; set; }
        public Nullable<bool> qtstatus_qc_sbmt { get; set; }
        public Nullable<bool> qtstatus_sls_sbmt { get; set; }
        public Nullable<bool> qtstatus_lock { get; set; }
        public Nullable<bool> qtstatus_output { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
