//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grppix
    {
        public int grppix_id { get; set; }
        public Nullable<int> grppix__grphdr_pix_id { get; set; }
        public byte[] qrppix_pix { get; set; }
        public Nullable<int> grppix_order { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
