//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_X_grpcomp
    {
        public int grpcompX_grphdr_id { get; set; }
        public int grpcomX_comp_id { get; set; }
        public int ID { get; set; }
    
        public virtual tbl_comp tbl_comp { get; set; }
        public virtual tbl_grpHdr tbl_grpHdr { get; set; }
    }
}
