//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_qtdtl
    {
        public int qtdtl_qthdr_qn { get; set; }
        public int qtdtl_comp_id { get; set; }
        public Nullable<int> qtdtl_comp_qty { get; set; }
        public Nullable<bool> qtdtl_sub { get; set; }
        public string qtdtl_comp_case { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
