//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_formulas
    {
        public int id { get; set; }
        public string formula_name { get; set; }
        public string formula_locn { get; set; }
        public Nullable<double> formula_labor_rate { get; set; }
        public Nullable<double> formula_labor_time { get; set; }
        public Nullable<double> formula_labor_factor { get; set; }
        public Nullable<double> formula_OH { get; set; }
        public Nullable<double> formula_GA { get; set; }
        public Nullable<double> formula_finance { get; set; }
        public Nullable<double> formula_warehouse { get; set; }
        public Nullable<double> formula_inlndfrgt { get; set; }
        public Nullable<int> formula_inlndfrgt_size { get; set; }
        public Nullable<double> formula_oceanfrgt { get; set; }
        public Nullable<double> formula_oceanfrgt_size { get; set; }
        public Nullable<double> formula_imprtdty { get; set; }
        public Nullable<double> formula_excisetx { get; set; }
        public Nullable<double> formula_MAR { get; set; }
        public Nullable<double> formula_strlzn { get; set; }
        public Nullable<int> formula_strlzn_load { get; set; }
        public Nullable<double> formula_import_ship_rate { get; set; }
        public Nullable<System.DateTime> formula_updtdate { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
