//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grpLbl
    {
        public int id { get; set; }
        public Nullable<int> grpLbl_hdr_id { get; set; }
        public Nullable<bool> grpLbl_ConsultIFU { get; set; }
        public Nullable<bool> grpLbl_SingleUse { get; set; }
        public string grpLbl_CEclass { get; set; }
        public Nullable<bool> grpLbl_Dry { get; set; }
        public Nullable<bool> grpLbl_Caution { get; set; }
        public Nullable<bool> grpLbl_Latex { get; set; }
        public Nullable<bool> grpLbl_StoreDark { get; set; }
        public Nullable<bool> grpLbl_Resterilize { get; set; }
        public Nullable<bool> grpLbl_MfgDate { get; set; }
        public Nullable<bool> grpLbl_Expry { get; set; }
        public Nullable<bool> grpLbl_Flame { get; set; }
        public Nullable<bool> grpLbl_Damage { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
