//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_boxes
    {
        public int id { get; set; }
        public string box_desc { get; set; }
        public string box_brand { get; set; }
        public Nullable<double> box_lngth { get; set; }
        public Nullable<double> box_wdth { get; set; }
        public Nullable<double> box_hght { get; set; }
        public Nullable<double> box_wght { get; set; }
        public Nullable<bool> box_active { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
