//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_acct
    {
        public int id { get; set; }
        public string acct_name { get; set; }
        public string acct_city { get; set; }
        public string acct_state { get; set; }
        public string acct_cntry { get; set; }
        public string acct_3code { get; set; }
        public Nullable<double> acct_whrhs { get; set; }
        public Nullable<double> acct_frght { get; set; }
        public Nullable<double> acct_misc { get; set; }
        public Nullable<double> acct_logstcs { get; set; }
        public Nullable<double> acct_admin { get; set; }
        public Nullable<System.DateTime> acct_contract_start { get; set; }
        public Nullable<System.DateTime> acct_contract_end { get; set; }
        public Nullable<int> acct_assoc { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
