//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_CEclass
    {
        public string CEclass_ID { get; set; }
        public Nullable<int> CEclass_order { get; set; }
        public string CEclass_desc { get; set; }
        public string CEclass_risk { get; set; }
        public string CEclass_expl { get; set; }
    }
}
