//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_strlty
    {
        public int id { get; set; }
        public string strlty_desc { get; set; }
        public string strlty_mean { get; set; }
        public byte[] strlty_symbol { get; set; }
        public string strtly_refno { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
