//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_grpFAB
    {
        public int id { get; set; }
        public Nullable<int> grpFAB_hdr_id { get; set; }
        public string grpFAB_Feat { get; set; }
        public string grpFAB_Ben { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
    }
}
