//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_comp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_comp()
        {
            this.tbl_lbl = new HashSet<tbl_lbl>();
            this.tbl_pix = new HashSet<tbl_pix>();
            this.tbl_purch = new HashSet<tbl_purch>();
            this.tbl_X_cat = new HashSet<tbl_X_cat>();
            this.tbl_X_grpcomp = new HashSet<tbl_X_grpcomp>();
            this.tbl_X_material = new HashSet<tbl_X_material>();
            this.tbl_X_ref = new HashSet<tbl_X_ref>();
            this.tbl_X_spclty = new HashSet<tbl_X_spclty>();
            this.tbl_X_ref1 = new HashSet<tbl_X_ref>();
        }
    
        public int id { get; set; }
        public Nullable<int> comp_vend_id { get; set; }
        public Nullable<int> comp_mfgr_id { get; set; }
        public string comp_vend_pn { get; set; }
        public string comp_brand { get; set; }
        public string comp_desc_orig { get; set; }
        public string comp_desc_noun { get; set; }
        public string comp_desc_attrbt { get; set; }
        public string comp_desc_adj { get; set; }
        public string comp_desc_alt { get; set; }
        public string comp_desc_kywrd { get; set; }
        public string comp_desc_color { get; set; }
        public string comp_desc_side { get; set; }
        public string comp_size_imp { get; set; }
        public string comp_size_met { get; set; }
        public string comp_coo_id { get; set; }
        public Nullable<int> comp_strlty { get; set; }
        public Nullable<int> comp_status_id { get; set; }
        public Nullable<double> comp_HS_code { get; set; }
        public Nullable<int> comp_moq { get; set; }
        public string comp_ERP_PN { get; set; }
        public Nullable<bool> comp_npe { get; set; }
        public Nullable<int> comp_pm { get; set; }
        public string comp_source { get; set; }
        public byte[] SSMA_TimeStamp { get; set; }
        public string x { get; set; }
    
        public virtual tbl_coo tbl_coo { get; set; }
        public virtual tbl_vend tbl_vend { get; set; }
        public virtual tbl_prodmgr tbl_prodmgr { get; set; }
        public virtual tbl_stat tbl_stat { get; set; }
        public virtual tbl_vend tbl_vend1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_lbl> tbl_lbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_pix> tbl_pix { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_purch> tbl_purch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_X_cat> tbl_X_cat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_X_grpcomp> tbl_X_grpcomp { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_X_material> tbl_X_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_X_ref> tbl_X_ref { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_X_spclty> tbl_X_spclty { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_X_ref> tbl_X_ref1 { get; set; }
    }
}
