//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_vendDtl
    {
        public int vendDtl_vend_id { get; set; }
        public int vendDtl_dtl_id { get; set; }
        public string vendDtl_conct_lname { get; set; }
        public string vendDtl_conct_fname { get; set; }
        public string vendDtl_conct_email { get; set; }
        public string vendDtl_conct_phone { get; set; }
        public string vendDtl_conct_mobile { get; set; }
        public string vendDtl_conct_notes { get; set; }
    }
}
