//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasterCollateralLibrary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_rep
    {
        public int id { get; set; }
        public string rep_fname { get; set; }
        public string rep_lname { get; set; }
        public string rep_title { get; set; }
        public string rep_phone { get; set; }
        public string rep_mobile { get; set; }
        public string rep_email { get; set; }
        public string rep_address1 { get; set; }
        public string rep_address2 { get; set; }
        public string rep_city { get; set; }
        public string rep_state { get; set; }
        public string rep_zip { get; set; }
        public string rep_country { get; set; }
        public Nullable<int> rep_company { get; set; }
    }
}
